### PR TITLE
Tets/userbundle controler

### PR DESCRIPTION
**Pull request by KarolisM**
added tests for user controller response and log in form.

### CODE REVIEW

**Comment by povils** [comment]
net neziuresiu kodo, nes testai tavo failina:)

**Comment by KarolisM** [comment]
Keista, pas mane veikė, paziuresiu kas ne taip, zinoma.

**Comment by KarolisM** [comment]
Keisciausia tai, kad atlieka tris testus nors yra du parasyit.

**Comment by KarolisM** [comment]
Cia turbut su book testais :)

**Comment by KarolisM** [comment]
Na pas mane veikia: 
`vendor/bin/phpunit
PHPUnit 5.6.2 by Sebastian Bergmann and contributors.
..  2 / 2 (100%)
Time: 9.43 seconds, Memory: 16.00MB
OK (2 tests, 6 assertions)
`

**Pull request closed without merging**
